"""Generate complete startup script for PostHog development VMs."""

from config import RepoConfig


def generate_startup_script(
    posthog_branch: str = "master",
    additional_repos: list[RepoConfig] | None = None,
    enable_minimal_mode: bool = False,
) -> str:
    """Generate a complete startup script for PostHog development.

    The script:
    1. Updates system packages
    2. Installs Docker and Docker Compose
    3. Installs development dependencies (Python, Node, pnpm, uv, mprocs)
    4. Clones PostHog and optional additional repositories
    5. Prepares the environment for running bin/start

    Args:
        posthog_branch: Git branch for PostHog repo
        additional_repos: List of additional repos to clone
        enable_minimal_mode: Whether to configure for minimal mode

    Returns:
        Complete bash startup script as string
    """
    additional_repos = additional_repos or []

    # Build the additional repos clone commands
    additional_clone_commands = ""
    for repo in additional_repos:
        additional_clone_commands += f'''
echo ">>> Cloning {repo.url} (branch: {repo.branch})"
git clone --branch {repo.branch} {repo.url} /home/posthog-dev/{repo.target_dir}
chown -R posthog-dev:posthog-dev /home/posthog-dev/{repo.target_dir}
'''

    minimal_env = 'export POSTHOG_MINIMAL_MODE="true"' if enable_minimal_mode else ""
    start_cmd = "./bin/start --minimal" if enable_minimal_mode else "./bin/start"

    script = f'''#!/bin/bash
#
# PostHog Development VM Startup Script
# Generated by posthog-dev-pulumi
#
set -ex

LOG_FILE="/var/log/posthog-startup.log"
exec > >(tee -a "$LOG_FILE") 2>&1

echo "========================================"
echo "PostHog Dev VM Startup - $(date)"
echo "========================================"

# ========================================
# 1. System Updates
# ========================================
echo ">>> Updating system packages"
apt-get update
DEBIAN_FRONTEND=noninteractive apt-get upgrade -y

# ========================================
# 2. Install Docker
# ========================================
echo ">>> Installing Docker"
apt-get install -y \\
    apt-transport-https \\
    ca-certificates \\
    curl \\
    gnupg \\
    lsb-release \\
    software-properties-common

# Add Docker's official GPG key
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

# Set up the repository
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

apt-get update
apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

# Configure Docker for better performance
cat > /etc/docker/daemon.json << 'DOCKEREOF'
{{
    "log-driver": "json-file",
    "log-opts": {{
        "max-size": "100m",
        "max-file": "3"
    }},
    "storage-driver": "overlay2"
}}
DOCKEREOF

systemctl restart docker

# ========================================
# 3. Create Development User
# ========================================
echo ">>> Creating posthog-dev user"
if ! id posthog-dev &>/dev/null; then
    useradd -m -s /bin/bash posthog-dev
fi
usermod -aG docker posthog-dev

# ========================================
# 4. Install Development Dependencies
# ========================================
echo ">>> Installing development dependencies"

# Build essentials and common tools
apt-get install -y \\
    build-essential \\
    git \\
    curl \\
    wget \\
    vim \\
    htop \\
    jq \\
    unzip \\
    brotli \\
    libpq-dev \\
    libffi-dev \\
    libssl-dev \\
    python3-dev \\
    pkg-config

# Install Python 3.12 (required by PostHog)
echo ">>> Installing Python 3.12"
add-apt-repository -y ppa:deadsnakes/ppa
apt-get update
apt-get install -y python3.12 python3.12-venv python3.12-dev
update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.12 1
update-alternatives --install /usr/bin/python python /usr/bin/python3.12 1

# Install uv (fast Python package manager)
echo ">>> Installing uv"
curl -LsSf https://astral.sh/uv/install.sh | sh
# Make uv available system-wide
cp /root/.local/bin/uv /usr/local/bin/
chmod +x /usr/local/bin/uv

# Install Node.js 20 LTS
echo ">>> Installing Node.js 20"
curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
apt-get install -y nodejs

# Install pnpm
echo ">>> Installing pnpm"
npm install -g pnpm

# Install mprocs (process orchestrator)
echo ">>> Installing mprocs"
MPROCS_VERSION="0.7.1"
wget -q "https://github.com/pvolok/mprocs/releases/download/v${{MPROCS_VERSION}}/mprocs-${{MPROCS_VERSION}}-linux64.tar.gz" -O /tmp/mprocs.tar.gz
tar -xzf /tmp/mprocs.tar.gz -C /usr/local/bin/
chmod +x /usr/local/bin/mprocs

# Install Rust (needed for some PostHog components)
echo ">>> Installing Rust"
su - posthog-dev -c "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y"

# ========================================
# 5. Clone Repositories
# ========================================
echo ">>> Cloning PostHog repository (branch: {posthog_branch})"
git clone --branch {posthog_branch} https://github.com/posthog/posthog.git /home/posthog-dev/posthog
chown -R posthog-dev:posthog-dev /home/posthog-dev/posthog

{additional_clone_commands}

# ========================================
# 6. Setup PostHog Environment
# ========================================
echo ">>> Setting up PostHog environment"

# Create environment file
cat > /home/posthog-dev/posthog/.env << 'ENVEOF'
DEBUG=1
SKIP_SERVICE_VERSION_REQUIREMENTS=1
SECRET_KEY=dev-secret-key-not-for-production
DATABASE_URL=postgres://posthog:posthog@localhost:5432/posthog
REDIS_URL=redis://localhost:6379/
CLICKHOUSE_HOST=localhost
{minimal_env}
ENVEOF

chown posthog-dev:posthog-dev /home/posthog-dev/posthog/.env

# Download GeoLite2 database
echo ">>> Downloading GeoLite2 database"
su - posthog-dev -c "cd /home/posthog-dev/posthog && ./bin/download-mmdb" || true

# Install Python dependencies with uv
echo ">>> Installing Python dependencies"
su - posthog-dev -c "cd /home/posthog-dev/posthog && uv sync" || true

# Install Node dependencies
echo ">>> Installing Node dependencies"
su - posthog-dev -c "cd /home/posthog-dev/posthog && pnpm install" || true

# ========================================
# 7. Setup Shell Environment
# ========================================
echo ">>> Configuring shell environment"

cat >> /home/posthog-dev/.bashrc << 'BASHRCEOF'

# PostHog Development Environment
export PATH="$HOME/.cargo/bin:$HOME/.local/bin:$PATH"
export POSTHOG_DIR="$HOME/posthog"

# Convenience aliases
alias ph='cd $POSTHOG_DIR'
alias phstart='cd $POSTHOG_DIR && ./bin/start'
alias phminimal='cd $POSTHOG_DIR && ./bin/start --minimal'
alias phlogs='docker compose -f $POSTHOG_DIR/docker-compose.dev.yml logs -f'
alias phps='docker compose -f $POSTHOG_DIR/docker-compose.dev.yml ps'
alias phdown='docker compose -f $POSTHOG_DIR/docker-compose.dev.yml down'

echo ""
echo "========================================"
echo "PostHog Development VM Ready!"
echo "========================================"
echo ""
echo "Quick commands:"
echo "  phstart     - Start PostHog (full mode)"
echo "  phminimal   - Start PostHog (minimal mode)"
echo "  phlogs      - View Docker container logs"
echo "  phps        - Show Docker container status"
echo "  phdown      - Stop Docker containers"
echo ""
echo "PostHog directory: $POSTHOG_DIR"
echo ""
BASHRCEOF

chown posthog-dev:posthog-dev /home/posthog-dev/.bashrc

# ========================================
# 8. Final Setup
# ========================================
echo ">>> Running final setup"

# Increase system limits for Docker
cat >> /etc/sysctl.conf << 'SYSCTLEOF'
# Docker optimizations
vm.max_map_count=262144
fs.file-max=65536
SYSCTLEOF
sysctl -p

# Pre-pull Docker images to speed up first start
echo ">>> Pre-pulling Docker images (this may take a while)"
su - posthog-dev -c "cd /home/posthog-dev/posthog && docker compose -f docker-compose.dev-minimal.yml pull" || true

echo "========================================"
echo "PostHog Dev VM Startup Complete - $(date)"
echo "========================================"
echo ""
echo "To start PostHog:"
echo "  1. SSH into the VM"
echo "  2. Switch to dev user: sudo su - posthog-dev"
echo "  3. Start PostHog: {start_cmd}"
echo ""
'''

    return script
