"""Generate complete startup script for PostHog development VMs.

This module assembles the startup script from modular sections for easier
maintenance and extension. Each section is defined in the sections/ directory.
"""

from config import ClaudeCodeConfig, CodexCliConfig, GitHubCliConfig, MonitoringConfig, RemoteDesktopConfig, RepoConfig

from .sections import (
    # Base system setup
    get_system_updates,
    get_docker_install,
    get_flox_install,
    get_system_deps,
    get_user_creation,
    # Monitoring
    get_ops_agent_install,
    get_netdata_install,
    # Tools
    get_claude_code,
    get_github_cli,
    get_codex_cli_config,
    # Remote Desktop
    get_remote_desktop_install,
    get_remote_desktop_config,
    # PostHog
    get_clone_repos,
    get_posthog_env,
    get_hosts_config,
    get_flox_activate,
    get_docker_services,
    get_start_script,
    # Shell
    get_makefile,
    get_bashrc,
    get_sysctl_and_docker_pull,
    get_final_message,
)


def generate_startup_script(
    posthog_branch: str = "master",
    additional_repos: list[RepoConfig] | None = None,
    enable_minimal_mode: bool = False,
    monitoring: MonitoringConfig | None = None,
    claude_code: ClaudeCodeConfig | None = None,
    github_cli: GitHubCliConfig | None = None,
    remote_desktop: RemoteDesktopConfig | None = None,
    codex_cli: CodexCliConfig | None = None,
) -> str:
    """Generate a complete startup script for PostHog development.

    The script uses Flox (PostHog's recommended approach) which manages:
    - Python (via uv)
    - Node.js 22
    - mprocs
    - Rust toolchain
    - All other development dependencies

    Steps:
    1. Updates system packages
    2. Installs monitoring agents (GCP Ops Agent, Netdata)
    3. Installs Docker and Docker Compose
    4. Installs Flox
    5. Clones PostHog and optional additional repositories
    6. Activates Flox environment (installs all deps via on-activate hook)
    7. Installs Claude Code (optional)
    8. Installs Remote Desktop - XFCE + xrdp + Chrome (optional)
    9. Installs OpenAI Codex CLI (optional)

    Args:
        posthog_branch: Git branch for PostHog repo
        additional_repos: List of additional repos to clone
        enable_minimal_mode: Whether to configure for minimal mode
        monitoring: Monitoring agents configuration
        claude_code: Claude Code installation configuration
        remote_desktop: Remote desktop (xrdp) configuration
        codex_cli: OpenAI Codex CLI installation configuration

    Returns:
        Complete bash startup script as string
    """
    # Apply defaults
    additional_repos = additional_repos or []
    monitoring = monitoring or MonitoringConfig()
    claude_code = claude_code or ClaudeCodeConfig()
    github_cli = github_cli or GitHubCliConfig()
    remote_desktop = remote_desktop or RemoteDesktopConfig()
    codex_cli = codex_cli or CodexCliConfig()

    # Assemble script from sections
    script = f'''#!/bin/bash
#
# PostHog Development VM Startup Script
# Generated by posthog-dev-pulumi
#
# Uses Flox for dependency management (PostHog's recommended approach)
# See: https://posthog.com/handbook/engineering/developing-locally#setup-with-flox-recommended
#
set -euo pipefail
export HOME="${{HOME:-/root}}"

LOG_FILE="/var/log/posthog-startup.log"
TIMING_FILE="/var/log/posthog-startup-timing.log"
exec > >(tee -a "$LOG_FILE") 2>&1

SKIP_HEAVY=0
if [ -f /etc/posthog-base-image ]; then
    SKIP_HEAVY=1
    echo "Base image marker detected; skipping heavy bootstrap steps."
fi

PROJECT_ID=$(curl -s -H "Metadata-Flavor: Google" \
    http://metadata.google.internal/computeMetadata/v1/project/project-id)

fetch_secret() {{
    local secret_name="$1"
    if [ -z "$secret_name" ]; then
        echo ""
    else
    local token
    token=$(curl -s -H "Metadata-Flavor: Google" \
        http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token | \
        python3 -c 'import json,sys; print(json.load(sys.stdin)["access_token"])')
        curl -s -H "Authorization: Bearer $token" \
            "https://secretmanager.googleapis.com/v1/projects/${{PROJECT_ID}}/secrets/${{secret_name}}/versions/latest:access" | \
            python3 -c 'import base64,json,sys; print(base64.b64decode(json.load(sys.stdin)["payload"]["data"]).decode())'
    fi
}}

# Timing functions for measuring section duration
SCRIPT_START_TIME=$(date +%s)
SECTION_START_TIME=$SCRIPT_START_TIME

section_start() {{
    local section_name="$1"
    SECTION_START_TIME=$(date +%s)
    echo ""
    echo "========================================"
    echo ">>> [$section_name] Starting at $(date '+%H:%M:%S')"
    echo "========================================"
}}

section_end() {{
    local section_name="$1"
    local end_time=$(date +%s)
    local duration=$((end_time - SECTION_START_TIME))
    local total_elapsed=$((end_time - SCRIPT_START_TIME))
    echo ">>> [$section_name] Completed in ${{duration}}s (total: ${{total_elapsed}}s)"
    echo "$section_name,$duration,$total_elapsed" >> "$TIMING_FILE"
}}

echo "========================================"
echo "PostHog Dev VM Startup - $(date)"
echo "========================================"
echo "section,duration_sec,total_elapsed_sec" > "$TIMING_FILE"

{get_system_updates()}
{get_ops_agent_install(monitoring)}
{get_netdata_install(monitoring)}
{get_remote_desktop_install(remote_desktop)}
{get_docker_install()}
{get_user_creation()}
{get_claude_code(claude_code)}
{get_github_cli(github_cli)}
{get_remote_desktop_config(remote_desktop)}
{get_system_deps()}
{get_flox_install()}
{get_clone_repos(posthog_branch, additional_repos)}
{get_posthog_env(enable_minimal_mode)}
{get_hosts_config()}
{get_flox_activate()}
{get_codex_cli_config(codex_cli)}
{get_docker_services()}
{get_makefile()}
{get_start_script()}
{get_bashrc()}
{get_sysctl_and_docker_pull()}
{get_final_message()}
'''

    return script
