"""PostHog setup: clone, environment, migrations, Docker services, and screen session."""

from config import RepoConfig
from constants import POSTHOG_ENV_DEFAULTS


def get_clone_repos(posthog_branch: str, additional_repos: list[RepoConfig]) -> str:
    """Generate repository cloning section."""
    additional_clone_commands = ""
    for repo in additional_repos:
        branch_flag = f"--branch {repo.branch} " if repo.branch else ""
        branch_label = repo.branch or "default"
        additional_clone_commands += f'''
if [ -d /home/ph/{repo.target_dir}/.git ]; then
    echo "Repo {repo.url} already exists; fetching latest"
    su - ph -c "cd /home/ph/{repo.target_dir} && git fetch origin"
    su - ph -c "cd /home/ph/{repo.target_dir} && git pull --ff-only || true"
else
    echo ">>> Cloning {repo.url} (branch: {branch_label})"
    su - ph -c "git clone {branch_flag}{repo.url} /home/ph/{repo.target_dir}"
fi
'''

    return f'''
section_start "Clone Repositories"

# If repo exists, update it to latest
if [ -d /home/ph/posthog/.git ]; then
    echo "PostHog repo already exists; fetching latest"
    su - ph -c "git config --global --add safe.directory /home/ph/posthog"
    su - ph -c "cd /home/ph/posthog && git fetch origin"
    if git ls-remote --heads https://github.com/posthog/posthog.git {posthog_branch} | grep -q {posthog_branch}; then
        su - ph -c "cd /home/ph/posthog && git checkout {posthog_branch} || echo 'Warning: could not checkout {posthog_branch}'; git pull --ff-only || echo 'Warning: could not fast-forward {posthog_branch}'"
    else
        su - ph -c "cd /home/ph/posthog && git checkout master || echo 'Warning: could not checkout master'; git pull --ff-only || echo 'Warning: could not fast-forward master'"
    fi
else
# Check if branch exists remotely
if git ls-remote --heads https://github.com/posthog/posthog.git {posthog_branch} | grep -q {posthog_branch}; then
    echo "Branch '{posthog_branch}' exists, cloning directly"
    git clone --branch {posthog_branch} https://github.com/posthog/posthog.git /home/ph/posthog
else
    echo "Branch '{posthog_branch}' does not exist, cloning master and creating new branch"
    git clone https://github.com/posthog/posthog.git /home/ph/posthog
    cd /home/ph/posthog
    git checkout -b {posthog_branch}
    cd /
fi

chown -R ph:ph /home/ph/posthog

fi
section_end "Clone Repositories"

if [ -n "{' '.join([r.url for r in additional_repos])}" ]; then
    section_start "Clone Additional Repositories"
{additional_clone_commands}
    section_end "Clone Additional Repositories"
fi
'''


def get_posthog_env(enable_minimal_mode: bool) -> str:
    """Generate PostHog environment setup section."""
    env_lines = "\n".join(f"{k}={v}" for k, v in POSTHOG_ENV_DEFAULTS.items())
    if enable_minimal_mode:
        env_lines += "\nPOSTHOG_MINIMAL_MODE=true"

    return f'''
section_start "PostHog Environment"

# Create environment file
cat > /home/ph/posthog/.env << 'ENVEOF'
{env_lines}
ENVEOF

chown ph:ph /home/ph/posthog/.env

# Create simple PostHog start script (localhost access via Remote Desktop)
# Sets required env vars (DAGSTER_HOME, etc.) that bin/start computes from $0
cat > /home/ph/start-posthog.sh << 'STARTSCRIPTEOF'
#!/bin/bash
# PostHog start script for dev VM (localhost access via RDP)
# Generated by posthog-dev-pulumi startup script
#
# We set REPOSITORY_ROOT explicitly because bin/start computes it from $0,
# which doesn't work correctly when invoked through flox activate.
#
# Note: mprocs requires a proper TTY to function. When running in a detached
# screen/tmux session, we use 'script' to allocate a pseudo-terminal.

cd /home/ph/posthog

# Export env vars that bin/start normally sets (it can't compute them correctly
# when $0 is not the actual script path, e.g., when run through flox)
export REPOSITORY_ROOT=/home/ph/posthog
export LOCK_FILE="$REPOSITORY_ROOT/bin/start.lock"
export DAGSTER_HOME=$REPOSITORY_ROOT/.dagster_home
export DAGSTER_UI_PORT=${{DAGSTER_UI_PORT:-3030}}
export DAGSTER_UI_HOST=${{DAGSTER_UI_HOST:-localhost}}

# Use 'script' to allocate a pseudo-terminal for mprocs TUI
# The -q flag suppresses the "Script started" message
# /dev/null discards the typescript output file
FLOX_NO_DIRENV_SETUP=1 exec script -q -c 'flox activate -- bin/start --custom bin/mprocs-with-logging.yaml' /dev/null
STARTSCRIPTEOF

chmod +x /home/ph/start-posthog.sh
chown ph:ph /home/ph/start-posthog.sh
section_end "PostHog Environment"
'''


def get_hosts_config() -> str:
    """Generate /etc/hosts configuration section."""
    return '''
section_start "Hosts Config"
# Add required entries to /etc/hosts if not present (needed for Docker service resolution)
if ! grep -q "kafka clickhouse clickhouse-coordinator objectstorage" /etc/hosts; then
    echo "127.0.0.1 kafka clickhouse clickhouse-coordinator objectstorage" >> /etc/hosts
    echo "/etc/hosts amended for PostHog services"
else
    echo "/etc/hosts already contains required entries"
fi
section_end "Hosts Config"
'''


def get_flox_activate() -> str:
    """Generate Flox environment activation section."""
    return '''
section_start "Flox Activate"
if [ "$SKIP_HEAVY" = "1" ]; then
    echo "Skipping Flox activation (base image detected)"
    section_end "Flox Activate"
else
    echo "This installs all dependencies and may take several minutes on first run..."

# Run flox activate in non-interactive mode to install all dependencies
# The on-activate hook in .flox/env/manifest.toml handles:
# - Python environment setup (uv sync)
# - Node.js dependencies (pnpm install)
# Note: /etc/hosts already configured above (Flox can't sudo in non-interactive mode)
# FLOX_NO_DIRENV_SETUP=1 prevents interactive direnv setup prompt
su - ph -c "cd /home/ph/posthog && FLOX_NO_DIRENV_SETUP=1 flox activate -- echo 'Flox environment activated'" || true

# Download GeoLite2 database
echo "Downloading GeoLite2 database..."
su - ph -c "cd /home/ph/posthog && FLOX_NO_DIRENV_SETUP=1 flox activate -- ./bin/download-mmdb" || true
section_end "Flox Activate"
fi
'''


def get_docker_services() -> str:
    """Generate Docker services startup and migrations section."""
    return '''
section_start "Docker Services"
if [ "$SKIP_HEAVY" = "1" ]; then
    echo "Skipping Docker services (base image detected)"
    section_end "Docker Services"
else
# Use || true to continue even if some containers fail (e.g., port conflicts with otel-collector)
su - ph -c "cd /home/ph/posthog && docker compose -f docker-compose.dev.yml up -d" || true

echo "Waiting for Docker services to be ready..."
sleep 30

# Ensure critical services are running (db, redis, clickhouse, kafka)
echo "Verifying critical services..."
su - ph -c "cd /home/ph/posthog && docker compose -f docker-compose.dev.yml ps db redis clickhouse kafka"

echo "Running database migrations..."
su - ph -c "cd /home/ph/posthog && FLOX_NO_DIRENV_SETUP=1 flox activate -- bin/migrate" || true

echo "Generating demo data..."
su - ph -c "cd /home/ph/posthog && FLOX_NO_DIRENV_SETUP=1 flox activate -- python manage.py generate_demo_data" || true
section_end "Docker Services"
fi
'''


def get_start_script() -> str:
    """Generate PostHog start in screen session section."""
    return '''
section_start "Start PostHog"

# Note: mprocs requires an interactive terminal (TTY) to function properly.
# Instead of auto-starting in a detached session (which fails), we leave
# the environment ready for the user to start PostHog interactively.
#
# To start PostHog after connecting:
#   1. SSH: gcloud compute ssh <vm> && sudo su - ph && phstart
#   2. RDP: Open terminal and run: phstart
#
# The phstart alias runs: /home/ph/start-posthog.sh

echo ""
echo "=========================================="
echo "PostHog environment is ready!"
echo "=========================================="
echo ""
echo "Docker services are running."
echo "Database migrations have been applied."
echo "Demo data has been generated."
echo ""
echo "To start the PostHog dev server:"
echo "  1. Connect via SSH or Remote Desktop"
echo "  2. Run: phstart (or /home/ph/start-posthog.sh)"
echo ""
echo "This will launch mprocs with all PostHog services."
echo ""
section_end "Start PostHog"
'''
